[workspace]
resolver = "2"

members = ["crates/*"]

[workspace.dependencies]
# Dependencies that all use the same egui version
egui = "0.23"
bevy_egui = "0.22"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3