[workspace]
resolver = "2"

members = ["crates/*"]

[workspace.dependencies]
# Bevy
bevy = "0.11"
# Dependencies that all use the same egui version
egui = "0.23"
bevy_egui = "0.22"
egui_dock = "0.8"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
