[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path ="../common"}
bevy = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
bytemuck = "1.14"
